version: '3'
services:
  home_assistant:
    image: homeassistant/home-assistant
    container_name: home_assistant
    networks: 
      - HA_Network
    ports:
      - "${HA_PORT}:${HA_PORT}"
    volumes:
      - "${HA_CONFIG_PATH}:/config"
    
networks:
  HA_Network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_icc: 'true'
      com.docker.network.bridge.enable_ip_masquerade: 'true'
      com.docker.network.bridge.host_binding_ipv4: '0.0.0.0'
      com.docker.network.driver.mtu: '1350'
